### ISSUE TITLE
[contracts] feat: Implement Locking of Liquidity Provider (LP) Tokens for 6 Months

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/unruggable.meme#10]
# Issue: Implement Locking of Liquidity Provider (LP) Tokens for 6 Months

## Description

The objective of this issue is to implement a feature in the smart contract to lock the Liquidity Provider (LP) tokens for a period of six months. This locking mechanism is intended to enhance the trust and stability of the token by ensuring that liquidity is maintained in the market for a substantial period after launch.

## Requirements

1. **Locking Mechanism**: Develop a smart contract function or module that locks the LP tokens for a period of six months from the date of the liquidity being added to the pool.
2. **Time Tracking**: Implement a reliable and accurate time-tracking system within the contract to track the 6-month lock period.
3. **Unlocking Functionality**: After the lock period has elapsed, ensure that there is a secure and efficient mechanism for the LP tokens to be unlocked and made available.
4. **Transparency and Security**: Ensure that the locking mechanism is transparent and secure, providing confidence to token holders and liquidity providers.

## Implementation Notes

- Pay close attention to the accuracy and security of the time-lock mechanism.
- Ensure that the lock and unlock functionalities are resistant to common smart contract vulnerabilities.
- Consider the gas costs associated with these functionalities and optimize where possible.
- Thoroughly test the lock and unlock process, including edge cases around the timing of the lock period expiration.

**Comment by ermvrs** [comment]
I can take that

**Comment by abdelhamidbakhta** [comment]
> I can take that

Great, assigned to you
