### ISSUE TITLE
feat: disable tx_hash tracker after a certain delay

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#107]
To prevent multicall buys to the same recipient, we track the tx_hash and prevent to transfer twice to the same recipient in the same tx. 

However, this increases the costs of L1 commitment, for very little use past the initial launch. 
Therefore, this feature should be disabled once the `transfer_limit_delay` has expired.

**Comment by TAdev0** [comment]
@enitrat may I be assigned to this issue?
