### ISSUE TITLE
bug: `limit_delay` value is hardcoded in factory contract, while it shouldn't 

### ISSUE THREAD

**Issue by TAdev0** [keep-starknet-strange/unruggable.meme#111]
Factory contract uses `1000` for `limit_delay` value, without naming it. 
Is it the desired behaviour to fix  `limit_delay` to 1000 seconds? 
- If not, we should add one more parameter to `serialize_calldata` function. 
- if yes, we should declare a `limit_delay` variable to make the code easier to understand.

@enitrat  @abdelhamidbakhta  i can do this refactoring, just tell me which option is the good one.

**Comment by enitrat** [comment]
@TAdev0 i already took care of it in an open PR (or soon to be open)

**Comment by TAdev0** [comment]
@enitrat  i was reading your PR right now, indeed, i was about to close this issue. Sorry.

**Comment by enitrat** [comment]
all good!

BTW I am still working on cleaning a lot of mess. Hopefully by ~Monday things will be cleaner and easier to comprehend
