### ISSUE TITLE
feat: renounce ownership in `launch_memecoin`

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#113]
Once #112 is merged, we should renounce the ownership of the memecoin upon launching a memecoin.

**Comment by TAdev0** [comment]
@enitrat available to work on it tomorrow if no one is assigned !

**Comment by enitrat** [comment]
@TAdev0 ready

**Comment by TAdev0** [comment]
@enitrat  perfect, I will work on it tonight after 9pm CET
