### ISSUE TITLE
feat: deployment scripts of the unruggable contracts

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#119]
Create deployment scripts using the method of your choice - either StarknetJS or Starknet-Foundry (I am not sure SNFoundry is ready for this ATM, but this can be a good exploration). 

These scripts will:
- Deploy the `TokenLocker` contract with a `min_lock_time` set to 6 months (`15_721_200` seconds)
- Declare the `UnruggableMemecoin` contract to get its class hash
- Deploy the `Factory` contract with:
  -  the class hash of the unruggable memecoin
  - the list of supported exchanges (type `(SupportedExchange, ContractAddress)`)

**Comment by Bal7hazar** [comment]
I can take it
