### ISSUE TITLE
feat: add locker functionalities to the EkuboLauncher contract

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#125]
When the position is created, it is minted to the caller of the EkuboPositions contract, which is our own EkuboLauncher contract. 
The liquidity will thus be locked inside this contract, and we need to add locker functionalities to this contract.

- Add entrypoints allowing us to query the LP associated with a token
- Display details about this LP position (owner, current amount of token locked, fees gained). `get_lp_details(token: ContractAddress)`;
- Enable the withdrawing of Counteryparty token fees for this token. 
  - We dont want the LP owner to be able to withdraw any base tokens, only counterparty fees.
  - As the LP owner didn't deposit any counterparty tokens, he shouldn't be able to get ownership of his LP position _ever_
  - The only thing he can do is collect fees in the base token.
  - Only the LP owner can withdraw fees
- Enable the LP owner to transfer the LP to another owner `transfer_lp_ownership`
- Track the LPs per owner / per token LP

**Comment by cpp-phoenix** [comment]
@enitrat I can work on it. If you aren't working on it can you please assign it to me

**Comment by enitrat** [comment]
Sorry this was actually a duplicate of #127 which is closed now
