### ISSUE TITLE
design: improve multicall mechanism

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#126]
The multicall mechanism currently protects against a transaction when 1 account buys multiple times and sends to the same recipient.
But it doesn't protect against one buyer sending to N recipients. Thus, it is quite ineffective.

**Comment by TAdev0** [comment]
@enitrat issue available ?

**Comment by enitrat** [comment]
yeah if you can think of something efficient we can discuss. I don't see a clear way tbh

**Comment by TAdev0** [comment]
I Will take a look at it during the afternoon 👍

**Comment by TAdev0** [comment]
@enitrat  i was thinking about simply doing this : 

```
        #[inline(always)]
        fn ensure_not_multicall(ref self: ContractState) {
            let tx_hash: felt252 = get_tx_info().unbox().transaction_hash;
            assert(
                self.tx_hash_tracker.read(get_caller_address()) != tx_hash,
                'Multi calls not allowed'
            );
            self.tx_hash_tracker.write(get_caller_address(), tx_hash);
        }
```
This way, we store the tx hash with the caller address as key, and ensure that the sender of the tx cannot send to multiple recipients in the same tx.
