### ISSUE TITLE
feat: enable transfer of EkuboLP ownership

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#127]
In the EkuboLauncher contract, which handles the launch of a token on ekubo and holds the EkuboLP position, the owner of an LP position can only withdraw the accrued fees of the counterparty token.

In this feature, you will add a mechanism that enables the transfer of the ownership of this position.

Available as soon as the #124 pr is merged

**Comment by TAdev0** [comment]
@enitrat I'm interested if no one is assigned yet !

**Comment by TAdev0** [comment]
@enitrat  i think there's an issue with `launch_token` in launcher contract: it uses the callback to write to storage for `liquidity_positions` , but then , it is supposed to write in storage with these lines

```
           // Append the owner's position to storage. It can only be removed if the ownership
            // is transfered.
            let mut owner_positions = self.owner_to_positions.read(params.owner);
            owner_positions.append(id);
```

It feels like we just add `id` to some local variable, instead of writing onto storage.
could you confirm?

**Comment by enitrat** [comment]
we also have something similar in the Locker contract @TAdev0, you can reuse the remove_from_list function

**Comment by TAdev0** [comment]
thanks for precisions. I checked the library, indeed! really nice

**Comment by TAdev0** [comment]
@enitrat  I have another question : as i understand it, this contract will create only one position when `launch_token` is called, that's all. I don't understand how positions can be created?

**Comment by enitrat** [comment]
positions are created by Ekubo, minted to the Launcher contract, we only store the corresponding ID of the NFT and custody the NFT position for the owner. So what happens when we transfer ownership is that we only change the owner of the custodied NFT in our contract

**Comment by TAdev0** [comment]
ooooh okay. yeah for this issue, i knew that i just had to do that, but i didn't really understand the ''flow'' , thanks!!

**Comment by enitrat** [comment]
yes, same as in the LockManager contract

**Comment by TAdev0** [comment]
of course :p

**Comment by TAdev0** [comment]
should the caller provide a specific ID to transfer only one position and not all of his positions? i guess yes?

**Comment by enitrat** [comment]
Yes
