### ISSUE TITLE
feat: staking

### ISSUE THREAD

**Issue by Bal7hazar** [keep-starknet-strange/unruggable.meme#128]
Staking (or Stacking or Farming, I think Staking is the most miss used term for this) consists in providing the ability to users to lock their tokens into a pool/vault and be rewarded with the same token along a defined period of time.
It helps to reduce the circulating supply and then should artificially increase the price of the token.

The bigger and longer the user stakes, the better the reward they can claim.

Here is what I have in mind, there are 2 scenarios with different UX:

Option A:

As a owner, you want to:
- Deploy a pool with an amount of token `amount` and a linear distribution between `start_time` and `end_time` that cannot be revoked. Also you want to manage the `cooldown` period the users can withdraw their deposit from the pool.

As a degen, you want to:
- Deposit a quantity of token, receive a non-fungible token corresponding to your share at the timestamp you get in
- Claim your claimable thanks to: your deposit timestamp, claim timestamp and your share (all associated to the token_id), it burns the NFT
- Compound your NFT(s?) which will claim and deposit again (with the new timestamp and a reset on the cooldown)
- Withdraw your position after the cooldown period
- Trade your positions on marketplaces

Option B:

Same but with a fungible $sToken (EIP4626-style), not sure how to handle the locked time reward except if we have a deposit period and another withdraw period so the total locked time period is the same for everyone and rewards can be distributed exclusively based on the user shares.

I personally prefer option A since there is no period in which a user cannot deposit and their is no limited pool size, however the user canno degen++ on its position because it is an NFT.

**Comment by MyhGamer** [comment]
based

**Comment by cpp-phoenix** [comment]
Hey @Bal7hazar, Will this be part of Phase 2 or MVP ? I can work on it.

**Comment by Bal7hazar** [comment]
Hello @cpp-phoenix actually I think it could come after, we should wait for @enitrat to kickstart it if accepted.
I wanted to work on it but I guess we can work together.

**Comment by enitrat** [comment]
MVP phase is already finished, we're waiting for audits to end to move on

**Comment by 0xChqrles** [comment]
Closing this issue to split it into multiple smaller issues
