### ISSUE TITLE
announce date when unruggable will be on mainnet

### ISSUE THREAD

**Issue by MyhGamer** [keep-starknet-strange/unruggable.meme#129]
announce date when unruggable will be on mainnet

**Comment by enitrat** [comment]
No specific date yet. Contracts are almost ready, and then we need to
- Build the frontend
- Audit the contracts
- Deploy the contracts
- Ensure everything works as intended

**Comment by 3ameth** [comment]
When will deploy on mainnet ? it is after $STARK Launch ?
