### ISSUE TITLE
feat: launching with `unlock_time` set to 0 burns the token

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#186]
A great feature would be to burn the tokens if the `unlock_time` supplied is 0 when launching with Jediswap, so that there's even less risk of a rug.

**Comment by cpp-phoenix** [comment]
I can work in it @enitrat

**Comment by enitrat** [comment]
sure, but please submit something before tomorrow 12 UTC

**Comment by enitrat** [comment]
@cpp-phoenix any update?

**Comment by cpp-phoenix** [comment]
I'm working on it @enitrat, Give me a few more hours :)

**Comment by enitrat** [comment]
@cpp-phoenix change of plan: make it so that it's burnt if the unlock time is the maximum value that fits in a u64

**Comment by cpp-phoenix** [comment]
Okay, no change in case of 0?

**Comment by enitrat** [comment]
yeah, no change

**Comment by enitrat** [comment]
hi @cpp-phoenix we need this before 12UTC today imperatively

**Comment by cpp-phoenix** [comment]
@enitrat  I've done the changes. Facing some version conflict during compilation. Resolving that rn

**Comment by enitrat** [comment]
you can open a PR maybe I can take a look

**Comment by cpp-phoenix** [comment]
I'm facing difficulty is setting a 0 contract address to burn tokens.  How do we set contract address as 0 in Cairo. In solidity it's simply address(0) 

`pair.transfer(pair.contract_address.zero(), liquidity_received);`

**Comment by enitrat** [comment]
`pair.transfer(0.try_into().unwrap(), liquidity_received)`
or 
`pair.transfer(contract_address_const::<0>::(), liquidity_received)`

**Comment by enitrat** [comment]
Closed by #195
