### ISSUE TITLE
feat: Limitting user inputs for ekubo launch

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/unruggable.meme#189]
The following values are passed by the user and used for the creation of liquidity on Ekubo.

```rust
struct EkuboPoolParameters {
    fee: u128,
    tick_spacing: u128,
    // the sign of the starting tick is positive (false) if quote/token < 1 and negative (true) otherwise
    starting_price: i129,
    // The LP providing bound, upper/lower determined by the address of the LPed tokens
    bound: u128,
}
```
My opinion is token creator shouldn't set fees, tick_spacing, and bounds.

If a token creator sets too much fee, it is unfair.
If the token creator sets too low tick_spacing. Then, initial liquidity can be used so quickly.
If the token creator sets a low bound. Then the price can't go higher than that bound.

I am suggesting to calculate these values and use hard-coded values. Only the starting price should be asked of the user. Although it has to be inputted as u128 however, there cant be a negative starting price :) We can prepare i129 value before calling ekubo

**Comment by enitrat** [comment]
agreed

**Comment by enitrat** [comment]
After reflecting a bit I propose another solution, which is to restrict the tick spacing and fee of the pool to be inside a specific bound, e.g
Fee should be <5%
Tick spacing should be in [0.6, 2%]

The reasons is that the pool creation can't get frontran with non-hardcoded params, and if it were, we can adapt and launch with other parameters
