### ISSUE TITLE
feat: create pair and add liquidity on AMM in `launch_memecoin` function

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/unruggable.meme#2]
# Issue: Implement Pair Creation and Liquidity Addition in `launch_memecoin` Function

## Description

We need to enhance the `launch_memecoin` function to include the creation of a trading pair and the addition of liquidity to an Automated Market Maker (AMM) platform. This process involves using the Memecoin contract's internal balances (both the memecoin itself and a counterparty token like ETH or USDT) to establish the initial liquidity in the trading pool.

## Requirements

1. **Pair Creation**: Implement functionality within `launch_memecoin` to create a trading pair for Memecoin and a counterparty token (e.g., USDT, ETH) on the selected AMM platform.
2. **Liquidity Addition**: Modify `launch_memecoin` to use the internal balances of Memecoin (MT) and the counterparty token, which are sent to the Memecoin contract address, to add liquidity to the newly created trading pair.

## Example Workflow

- Memecoin (MT) is deployed at address `0xAA`.
- The owner sends `1000 MT` tokens and `1000 USDC` to address `0xAA`.
- The `launch_memecoin` function utilizes these internal balances (`1000 MT` and `1000 USDC`) to add liquidity to the MT/USDC pair on the selected AMM.

## Implementation Notes

- Ensure that the function checks for sufficient balances of both tokens before attempting to add liquidity.
- Consider gas optimization and security practices while implementing the liquidity addition process.
- Implement error handling for scenarios where the pair creation or liquidity addition fails.

**Comment by rcatalan98** [comment]
gm! please also @dubzn
