### ISSUE TITLE
[frontend] chart / explorer links

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#212]
On the memecoin page `/token/[addr]`, add a link to the token page (on starkscan or voyager).

If the token is launched, also add a link to the Dexscreener chart (Only JediSwap and Ekubo are supported on Dexscreener for the moment).

*For the Dexscreener link of memecoins launched on Ekubo, you'll need the tick spacing and the bounds fees.

**Comment by JoshdfG** [comment]
Can i work on this?

**Comment by 0xChqrles** [comment]
Sorry for the late reply, I've assigned it to you 👌

**Comment by abdegenius** [comment]
Seems this issue is still open! Has it been fixed or can i hop on it. Will get it done as soon as possible!

**Comment by mananbordia** [comment]
@0xChqrles Can you please review this PR: https://github.com/keep-starknet-strange/unruggable.meme/pull/219 and assign the issue to me ?
