### ISSUE TITLE
[Frontend] SDK integration

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#227]
Atm I'm writing this, the SDK is not ready yet, but once it's ready, a lot of the frontend logic should be removed and replaced using the SDK.

If that suits you @ugur-eren I can assign this one to you.

**Comment by KodeSage** [comment]
HI @0xChqrles please I would want to work on this

**Comment by 0xChqrles** [comment]
Hi @KodeSage I'd like to assign this one to @ugur-eren if possible. He's developing the SDK, so it will be easier for him, but I'll add a lot of new issues in the following hours, I can give you another one 👌

**Comment by KodeSage** [comment]
Hello @0xChqrles , alright, I'm looking forward to it.

**Comment by ugur-eren** [comment]
Hi @0xChqrles I would love to work on it, you can assign it to me
