### ISSUE TITLE
[Documentation] initiate package

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#228]
We need to set up a dedicated "Docs" page to help both new users and developers better understand how the project works. This documentation should include comprehensive guides, API references, and general information about the project.

The "Docs" page should be built using Docusaurus or another suitable static site documentation generator, providing a clean and navigable interface. Initially, we will not focus on content creation; the task here is to establish the framework in which the documentation will reside.

Please note:
- The "Docs" pages will be hosted in `packages/docs`
- It should support markdown for easy content updates and contributions in the future.

You can get inspiration at [Uniswap docs](https://github.com/Uniswap/docs) for instance.

---

_Please, before contributing, keep in mind that Unruggable prioritizes security and UX above everything else_

**Comment by raizo07** [comment]
Hello @0xChqrles kindly assign me to this.

**Comment by Ugo-X** [comment]
Hello @0xChqrles My name is Ugo, a full stack dev currently learning Cairo. i would love to contribute to this effort. Please can i be assigned this task? will get it done in no time

**Comment by 0xChqrles** [comment]
Hey all ! To keep things fair, I'll assign the issue to the first on you asked for it. But I'll add more issues very soon, stay tuned in the telegram group

**Comment by raizo07** [comment]
Hello @0xChqrles I'd like to send you a DM. What platform can I best reach you on? Telegram?

**Comment by Osatuyi** [comment]
@0xChqrles , please can you share the telegram group link? I'll like to get alerted whenever you post about another issue.

**Comment by Osatuyi** [comment]
Hello @0xChqrles , how will I be able to identify you on the telegram platform? I'll like to work on an issue when you post new ones.
