### ISSUE TITLE
[Backend] init apibara

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#232]
Init apibara indexing in a new `/packages/backend` section. It should index:

- Memecoins transfers
- Factory launchs

**Comment by bhavyagosai** [comment]
hey

**Comment by Rhumsteak** [comment]
Hi Chqrles, can you assign it to me please ?

**Comment by bhavyagosai** [comment]
Understandable! I am not in the tg group yet, can I get an invite link or from where can I join it for better updates/communication?  @0xChqrles

**Comment by 0xChqrles** [comment]
Sure ! https://t.me/UnruggableMeme

**Comment by nicosanc** [comment]
I'd like a chance to work on this, if it hasn't been resolved yet
