### ISSUE TITLE
[SDK] AVNU integration to buy/sell

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#244]
Add some hooks allowing users to easily buy/sell tokens using AVNU quotes. You should be able to specify a slippage, tokens to buy/sell (we'll only support unrug memecoins and [quote tokens](https://github.com/keep-starknet-strange/unruggable.meme/blob/main/packages/core/src/constants/tokens.ts#L84)), and an amount to spend or buy.

you can get AVNU quotes this way: [`useAvnu.ts`](https://github.com/sakupenlabs/zapper/blob/main/src/hooks/useAvnu.ts)

These new hooks should allow the development of #226 

---

Looking forward to assign this issue to @rfulop

**Comment by rfulop** [comment]
Hey @0xChqrles ! I would like to take this issue
