### ISSUE TITLE
Fair ICO to solve low initial liquidity

### ISSUE THREAD

**Issue by Flydexo** [keep-starknet-strange/unruggable.meme#40]
Crowfunding method for memecoins to solve the low initial liquidity problem. You don't launch the token directly on AMM, it is beforehand on a "campaign" where the deployer sets a price per token and token supply (%), this part is sold as an ICO. Before the campaign ends, the tokens and eth are locked. The campaign lasts for e.g. 1 day, after this delay if all the tokens were sold the eth is used to create the initial lp and the buyers from the ICO can claim their tokens after some delay (avoid instant dump).  If not all the tokens were sold, users can claim back their eth.

**Comment by enitrat** [comment]
if the liquidity is supplied in a uni-v4 style AMM (ekubo?) Can't you just provide liquidity with a single side, starting from a tick higher than 0, which is considered the initial price of the token?

That would solve this problem pretty easily

**Comment by cpp-phoenix** [comment]
Is there any changes needed here?

**Comment by imotai** [comment]
This is a great feature! Is there any update ?
