### ISSUE TITLE
[frontend] token deployment 

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#42]
Allow the launch form to actually deploy a token. The contract address should be stored in local storage through zustand persisting slice.

**Comment by Flydexo** [comment]
What do you want atm ? A basic ERC20 for illustration purposes or the current version of the contracts ?

**Comment by codingmickey** [comment]
Hey @Flydexo or @0xChqrles any help I can assist you with on this?

**Comment by 0xChqrles** [comment]
@Flydexo we’re going for a factory contract finally.

Thanks @codingmickey ! I let you check with @Flydexo, I’m not working on this issue

**Comment by fracek** [comment]
The current frontend deploys the token trough the udc.
