### ISSUE TITLE
[frontend] token mgmt page

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/unruggable.meme#44]
Create the token mgmt page at `/manage/[tokenAddress]`

if the connected wallet is the owner of the contract, it should display a form, otherwise, we can redirect to `/manage`

the owner form allows to distribute liquidity (like in the launch page), you can see the safety score of the token based on the amount distributed (the more in the pool, the safer). And you can launch the token on the pool of your choice

**Comment by codingmickey** [comment]
(I'm really sorry for asking basic questions around here..)
If I want to proceed with this how should I do it? Like any references or something to begin with?

**Comment by abdelhamidbakhta** [comment]
> (I'm really sorry for asking basic questions around here..) If I want to proceed with this how should I do it? Like any references or something to begin with?

are you in the telegram group ? it will be easier for coordination.
https://t.me/UnruggableMeme

**Comment by codingmickey** [comment]
> > (I'm really sorry for asking basic questions around here..) If I want to proceed with this how should I do it? Like any references or something to begin with?
> 
> are you in the telegram group ? it will be easier for coordination. https://t.me/UnruggableMeme

yes yes I'm there too (as @codingmickey)

**Comment by cpp-phoenix** [comment]
Hey, Is it done?
