### ISSUE TITLE
feat: implement maximum team allocation percentage before launch

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/unruggable.meme#5]
# Issue: Implement Maximum Team Allocation Percentage in Smart Contract

## Description

The goal of this issue is to establish a cap on the percentage of the total token supply that can be allocated to the team. This measure is intended to prevent excessive control over the token supply by the team, promoting a more equitable and decentralized token distribution.

## Requirements

1. **Maximum Team Allocation Constant**: Define a constant, `MAX_SUPPLY_PERCENTAGE_TEAM_ALLOCATION`, and set it to `10%`. This will represent the maximum percentage of the total token supply that can be allocated to the team.
2. **Implementation in Token Distribution**: Ensure that this constant is enforced during the token distribution process. If any allocation attempt exceeds this limit, the transaction should fail with an appropriate error message.
3. **Documentation and Comments**: Clearly document this constant and its usage in the codebase, explaining its purpose and the rationale behind the `10%` limit.

## Implementation Notes

- The implementation should be integrated seamlessly with the existing token distribution logic.
- Prioritize security and simplicity in the code to prevent any loopholes or unintended behaviors.
- Include unit tests to validate that the team allocation does not exceed the defined maximum percentage and to ensure that token distribution adheres to this constraint under various scenarios.

## Additional Context

Setting a cap on team allocation is a vital aspect of ensuring a fair and balanced ecosystem for the memecoin. It addresses potential concerns about centralization and offers reassurance to the community and investors about the equitable distribution of tokens.

**Comment by 0xEniotna** [comment]
Can I take this one ?

**Comment by abdelhamidbakhta** [comment]
> Can I take this one ?

Sure, assigned to you
