### ISSUE TITLE
[contract] feat: Implement Initial Token Distribution in Constructor

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/unruggable.meme#60]
# Issue: Implement Initial Token Distribution in Constructor

## Description

This issue explores the possibility of handling the initial token distribution directly in the constructor of the Unruggable Memecoin contract. The proposal is to pass arrays of holders and their respective token amounts into the constructor, thereby conducting the distribution at the time of deployment. This approach could simplify several aspects of the contract's operation, including transfer restrictions and holder tracking prior to the launch.

## Discussion Points

1. **Distribution via Constructor**: Assess the feasibility and advantages of performing the initial distribution through the contract constructor.
2. **Simplification of Transfer Restrictions**: Explore how this method simplifies the process of disabling transfers post-initial distribution and until the `launch_memecoin` function is called.
3. **Reduction of On-Chain Tracking Needs**: Evaluate the impact on the need for tracking initial holders on-chain.
4. **Flexibility in Ownership and Recipient Roles**: Consider how this approach maintains flexibility in defining different entities as owners and initial recipients.

## Implementation Considerations

- Ensure the constructor can efficiently handle an array of holders and token amounts without exceeding gas limits.
- Develop robust error handling and validation for the input arrays to prevent any discrepancies in the distribution process.
- Thoroughly test the constructor's distribution logic to ensure accuracy and reliability.
- Maintain clarity and transparency in the contract's code and documentation regarding the distribution process.

## Pros and Cons

- **Pros**:
  - Simplifies contract logic by consolidating distribution into deployment.
  - Reduces the need for complex on-chain tracking mechanisms.
  - Maintains flexibility in roles and responsibilities within the contract.
- **Cons**:
  - Potentially higher deployment gas costs due to the inclusion of distribution logic in the constructor.
  - Requires careful input validation to ensure accurate and fair distribution.

**Comment by 0xEniotna** [comment]
Let me try something !

**Comment by abdelhamidbakhta** [comment]
> Let me try something !
sure mate!

**Comment by 0xEniotna** [comment]
This can be closed
