### ISSUE TITLE
[contracts] feat: Implement Protection Against Multicall Buys in Memecoin Launch

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/unruggable.meme#69]
# Issue: Implement Protection Against Multicall Buys in Memecoin Launch

## Description

This issue addresses the need for enhanced security measures in the Unruggable Memecoin project to protect against potential attack vectors that could arise from the multicall feature, specifically during the coin launch phase. The proposed solution involves utilizing `get_tx_info` to limit purchases not just per account address but also per transaction hash.

## Objective

To mitigate risks associated with multicall attacks where limits can be bypassed through multiple smart contract calls in the same transaction.

## Implementation

1. **Utilizing `get_tx_info`**: Incorporate the use of `get_tx_info` in the transaction validation logic to retrieve the transaction hash.
2. **Limit Per Transaction Hash**: Implement a mechanism that enforces buying limits per transaction hash, in addition to the existing per-account address limits.
3. **Integration with Buying Logic**: Ensure this security feature is seamlessly integrated with the current buying logic and does not impede legitimate transactions.

## Considerations

- **Efficiency**: Ensure the solution is gas-efficient and does not significantly increase transaction costs.
- **Compatibility**: Verify compatibility with existing smart contract functionalities and ensure no conflicts arise.
- **Testing**: Rigorously test the implementation to validate its effectiveness in preventing multicall buy attacks and to ensure it does not interfere with normal buying processes.

## Impact and Benefits

- **Enhanced Security**: Significantly reduces the risk of multicall buy attacks during the coin launch phase.
- **Fairness**: Ensures equitable buying opportunities for all participants by enforcing limits consistently.

**Comment by lana-shanghai** [comment]
Could I try this one? :D

**Comment by Mohiiit** [comment]
I can work on this one

**Comment by Mohiiit** [comment]
Hey, I have raised the PR #81

**Comment by cpp-phoenix** [comment]
Can this be closed or is there anything else needed to be done here?

**Comment by enitrat** [comment]
Closed in #81 (people remember to link PR to issues!)
