### ISSUE TITLE
[contract] feat: Ensure liquidity is locked in the constructor. 

### ISSUE THREAD

**Issue by 0xEniotna** [keep-starknet-strange/unruggable.meme#75]
# Issue: Ensure liquidity is locked in the constructor. 
The goal of this issue is to find a way to make the deployer lock liquidity in the contract to make sure the devs will indeed create a liquidity pool in an AMM. 

## Objective
This issue adds a new protection for the users as it forces the devs to launch with unruggable.

**Comment by 0xEniotna** [comment]
I take care of this myself !

**Comment by abdelhamidbakhta** [comment]
> I take care of this myself !

great, assigned to you

**Comment by 0xEniotna** [comment]
Not directly related but:

- modify the erc20 impl functions to avoid logic duplication in transfer and transfer_from between camel and snakecases

**Comment by 0xEniotna** [comment]
- add a whitelist for addresses
