### ISSUE TITLE
[frontend] feat: build launch form

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/unruggable.meme#8]
# Issue: Develop Launch Form for Memecoin Deployment

## Description

Create a user-friendly launch form interface for the deployment of the memecoin. This form will collect essential information required for deploying the token and setting up initial parameters. The form will culminate in a multi-call action that includes deploying the contract and executing a list of initial token transfers.

### Form Fields

1. **Token Name**: A field for the user to input the name of the token.
2. **Token Symbol**: A field for the user to input the symbol of the token.
3. **Initial Recipient Address**: A field for the address that will receive the minting supply at deployment. Include a button to auto-fill with the current connected address.
4. **Owner Address**: A field for the address that will have permissions to call the `launch_memecoin` function later. Include a button to auto-fill with the current connected address.
5. **Initial Holder Distribution**: A section for the user to add multiple addresses and specify the number of tokens each will receive. This should adhere to the maximum number of holders allowed before launch.

### Functionality

- Implement validation to ensure all inputs are correct and adhere to constraints (e.g., format of addresses, token name and symbol requirements, limits on initial holder distribution).
- The deploy action should bundle:
  - The contract deployment.
  - The list of transfers for initial distribution, based on the input from the initial holder distribution section.

## Implementation Notes

- Focus on creating a clear and intuitive user interface.
- Ensure robust error handling and user feedback for form validation.
- Optimize for a smooth and efficient multi-call transaction process.
- Test the form thoroughly, especially the interaction with blockchain transactions.

**Comment by abdelhamidbakhta** [comment]
@fracek we are done with the initalisation of this page. Do you plan to continue working on it to make it functional and interacting with the contracts ?

**Comment by fracek** [comment]
@abdelhamidbakhta Yeah, I need to update starknet react to work well with react forms, then I need a declared contract for testing. Will do the first today, the second once the contract is deployed.

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta Yeah, I need to update starknet react to work well with react forms, then I need a declared contract for testing. Will do the first today, the second once the contract is deployed.

great! so I'll keep this issue open so that you can reference it in follow up PRs

**Comment by cpp-phoenix** [comment]
He @abdelhamidbakhta I can work on it if it's not already done. Keen to take this up.
