### ISSUE TITLE
[frontend] feat: explanation page

### ISSUE THREAD

**Issue by JorikSchellekens** [keep-starknet-strange/unruggable.meme#89]
# Issue: Unruggable meme frontend needs an about section and tutorials

## Description
The page should clearly describe what the intention behind unruggable.meme is. i.e. don't get rekt. It should have clear links to this repository and, when it comes to it, to verified contract links on the explorers.

# Requirements
- Fun introductory paragraph describing what unruggable.meme is and its two main features: deploying and verifying unruggable contracts
- A clear description of why these coins are unruggable and the technical underpinnings which provide these guarantees. Some of this will seem to obvious to even bother explaining but put on a strong noob hat and go from there. (All contracts are from a verified class; class can / can't be updated, etc.)
- A clear description of what the risks still are (it is still a meme coin, go up go down)

# Implementation Notes
The page should be opinionated, fun and info-dense. This is the best way to instil confidence in the legitimacy of this system for the users who come across this page.

**Comment by okhaimie-dev** [comment]
I will like to give this a go if no one is working on it rn. @JorikSchellekens 

cc: @abdelhamidbakhta

**Comment by JorikSchellekens** [comment]
Go for it @okhaimie-dev, just a note, be very clear that unrugable.meme makes no statements about the coins value or future value, it simply restricts certain actions.

**Comment by JorikSchellekens** [comment]
@abdelhamidbakhta can you assign?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta can you assign?

yes done

**Comment by abdelhamidbakhta** [comment]
> I will like to give this a go if no one is working on it rn. @JorikSchellekens
> 
> cc: @abdelhamidbakhta

done

**Comment by okhaimie-dev** [comment]
@JorikSchellekens @abdelhamidbakhta 

I made an initial PR, just to make sure I am headed in the right direction. Waiting for y'alls review

**Comment by cpp-phoenix** [comment]
Hey, Is it done? Otherwise if there's anything I can help in please let me know

**Comment by Boreas09** [comment]
Hey there, if its not done i can continue. 

Thanks

**Comment by cpp-phoenix** [comment]
I'm already working on it @Boreas09 😊

**Comment by 0xChqrles** [comment]
Closing in favor of #228
