### ISSUE TITLE
feat: time-based disabling of multicall-prevention

### ISSUE THREAD

**Issue by enitrat** [keep-starknet-strange/unruggable.meme#95]
In the contracts, we prevent multicall-buy to avoid bots taking a good part of the supply at launch. 

However, this creates an overhead cost as we store inside a storage var _commited to L1_ the last tx_hash of the interaction from the sender of the transaction.

To prevent this, we can disable this security feature a certain amount of time after launch. I propose to keep it for the same time as for the buy limit delay, and disable it after.

**Comment by enitrat** [comment]
Depends on #81

**Comment by abdelhamidbakhta** [comment]
> In the contracts, we prevent multicall-buy to avoid bots taking a good part of the supply at launch.
> 
> However, this creates an overhead cost as we store inside a storage var _commited to L1_ the last tx_hash of the interaction from the sender of the transaction.
> 
> To prevent this, we can disable this security feature a certain amount of time after launch. I propose to keep it for 30 minutes, and disable it after.

Agreed, good idea
